@startuml

actor Client

participant BookController
participant BookService
participant BookRepo

database DB

participant OrderRepo
participant OrderService
participant OrderController

actor Manager


autonumber

Client -> BookController : getBook
activate BookController
    BookController -> BookService : findAllByFilters
    activate BookService
        BookService -> BookRepo : findAllByNameContainsIgnoreCaseAndGenreContainsIgnoreCase
        activate BookRepo
            BookRepo -> DB : select
            activate DB
                DB --> BookRepo
            deactivate DB
            BookRepo --> BookService
        deactivate BookRepo
        BookService --> BookController
    deactivate BookService
    BookController --> Client
deactivate BookController

Client -> OrderController : createOrder
activate OrderController
    OrderController -> BookService : findByIdAndInStockTrue
    activate BookService
        BookService -> BookRepo : findByIdAndInStockTrue
        activate BookRepo
            BookRepo -> DB : select
            activate DB
                DB --> BookRepo
            deactivate DB
            BookRepo --> BookService
        deactivate BookRepo
        BookService --> OrderController
    deactivate BookService
    OrderController --> Client
deactivate OrderController

Client -> OrderController : commitOrder
activate OrderController
    OrderController -> OrderService : addOrder
    activate OrderService
        OrderService -> OrderRepo : save
        activate OrderRepo
            OrderRepo -> DB : insert
            activate DB
                DB --> OrderRepo
            deactivate DB
            OrderRepo --> OrderService
        deactivate OrderRepo
        OrderService --> OrderController
    deactivate OrderService
    OrderController -> OrderService : findAllOrdersByClientId
    activate OrderService
        OrderService -> OrderRepo : findAllByClientIdAndForReturn
        activate OrderRepo
            OrderRepo -> DB : select
            activate DB
                DB --> OrderRepo
            deactivate DB
            OrderRepo --> OrderService
        deactivate OrderRepo
        OrderService --> OrderController
    deactivate OrderService
    OrderController --> Client
deactivate OrderController


Manager -> OrderController : getAllOrders
activate OrderController
    OrderController -> OrderService : findAllOrders
    activate OrderService
        OrderService -> OrderRepo : findAllByForReturn
        activate OrderRepo
            OrderRepo -> DB : select
            activate DB
                DB --> OrderRepo
            deactivate DB
            OrderRepo --> OrderService
        deactivate OrderRepo
        OrderService --> OrderController
    deactivate OrderService
    OrderController --> Manager
deactivate OrderController

Manager -> OrderController : approveOrder
activate OrderController
    OrderController -> OrderService : approveOrder
    activate OrderService
        OrderService -> OrderRepo : save
        activate OrderRepo
            OrderRepo -> DB : insert
            activate DB
                DB --> OrderRepo
            deactivate DB
            OrderRepo --> OrderService
        deactivate OrderRepo
        OrderService -> OrderRepo : deleteAllByBookIdAndApprovedFalse
        activate OrderRepo
            OrderRepo -> DB : delete
            activate DB
                DB --> OrderRepo
            deactivate DB
            OrderRepo --> OrderService
        deactivate OrderRepo
        OrderService --> OrderController
    deactivate OrderService
    OrderController --> Manager
deactivate OrderController


Client -> OrderController : getClientOrders
activate OrderController
    OrderController -> OrderService : findAllOrdersByClientId
    activate OrderService
        OrderService -> OrderRepo : findAllByClientIdAndForReturn
        activate OrderRepo
            OrderRepo -> DB : select
            activate DB
                DB --> OrderRepo
            deactivate DB
            OrderRepo --> OrderService
        deactivate OrderRepo
        OrderService --> OrderController
    deactivate OrderService
    OrderController --> Client
deactivate OrderController

Client -> OrderController : confirmOrder
activate OrderController
    OrderController -> OrderService : confirmOrder
    activate OrderService
        OrderService -> OrderRepo : save
        activate OrderRepo
            OrderRepo -> DB : insert
            activate DB
                DB --> OrderRepo
            deactivate DB
            OrderRepo --> OrderService
        deactivate OrderRepo
        OrderService --> OrderController
    deactivate OrderService
    OrderController --> Client
deactivate OrderController

Client -> BookController : getOwnBooks
activate BookController
    BookController -> BookService : findAllByOwnerIdAndFilters
    activate BookService
        BookService -> BookRepo : findAllByOwnerIdAndNameContainsIgnoreCaseAndGenreContainsIgnoreCase
        activate BookRepo
            BookRepo -> DB : select
            activate DB
                DB --> BookRepo
            deactivate DB
            BookRepo --> BookService
        deactivate BookRepo
        BookService --> BookController
    deactivate BookService
    BookController --> Client
deactivate BookController

@enduml
