@startuml

actor Client

participant BookController
participant BookService
participant BookRepo

database DB

participant OrderRepo
participant OrderService
participant OrderController

actor Manager

autonumber

Client -> BookController : getOwnBooks
activate BookController
    BookController -> BookService : findAllByOwnerIdAndFilters
    activate BookService
        BookService -> BookRepo : findAllByOwnerIdAndNameContainsIgnoreCaseAndGenreContainsIgnoreCase
        activate BookRepo
            BookRepo -> DB : select
            activate DB
                DB --> BookRepo
            deactivate DB
            BookRepo --> BookService
        deactivate BookRepo
        BookService --> BookController
    deactivate BookService
    BookController --> Client
deactivate BookController

Client -> OrderController : commitReturnRequest
activate OrderController
    OrderController -> OrderService : addRequest
    activate OrderService
        OrderService -> OrderRepo : save
        activate OrderRepo
            OrderRepo -> DB : insert
            activate DB
                DB --> OrderRepo
            deactivate DB
            OrderRepo --> OrderService
        deactivate OrderRepo
        OrderService --> OrderController
    deactivate OrderService
    OrderController --> Client
deactivate OrderController


Manager -> OrderController : getAllReturnRequests
activate OrderController
    OrderController -> OrderService : findAllRequests
    activate OrderService
        OrderService -> OrderRepo : findAllByForReturn
        activate OrderRepo
            OrderRepo -> DB : select
            activate DB
                DB --> OrderRepo
            deactivate DB
            OrderRepo --> OrderService
        deactivate OrderRepo
        OrderService --> OrderController
    deactivate OrderService
    OrderController --> Manager
deactivate OrderController


Manager -> OrderController : approveReturnRequest
activate OrderController
    OrderController -> OrderService : approveRequest
    activate OrderService
        OrderService -> OrderRepo : save
        activate OrderRepo
            OrderRepo -> DB : insert
            activate DB
                DB --> OrderRepo
            deactivate DB
            OrderRepo --> OrderService
        deactivate OrderRepo
        OrderService --> OrderController
    deactivate OrderService
    OrderController --> Manager
deactivate OrderController


Client -> BookController : getBook
activate BookController
    BookController -> BookService : findAllByFilters
    activate BookService
        BookService -> BookRepo : findAllByNameContainsIgnoreCaseAndGenreContainsIgnoreCase
        activate BookRepo
            BookRepo -> DB : select
            activate DB
                DB --> BookRepo
            deactivate DB
            BookRepo --> BookService
        deactivate BookRepo
        BookService --> BookController
    deactivate BookService
    BookController --> Client
deactivate BookController

@enduml